// next-gen/src/components/media/MediaItem.vue
<script lang="ts" setup>
import type { Media } from "@/model/Properties";
import IcoMoonSvg from "../IcoMoonSvg.vue";

defineProps<{
  media: Media;
}>();
</script>

<template>
  <a
    :href="media.link.includes('/') ? media.link : `#${media.link}`"
    :target="media.link ? '_blank' : '_self'"
    rel="noopener noreferrer"
  >
    <IcoMoonSvg :icon="media.icon" class-name="ico-cover" />
  </a>
</template>

// client/src/component/MainPage/CoverPage/MediaItem.tsx
import React from "react";
import IcoMoonSVG from "../../helper/IcomoonSVG";
import { MediaContent } from "./Media";

const MediaItem = ({ label, icon, link }: MediaContent) => {
  return (
    <a
      href={link.includes("/") ? link : `#${link}`}
      target={link ? "_blank" : "_self"}
      rel="noreferrer"
    >
      <IcoMoonSVG icon={icon} className="ico-cover" />
    </a>
  );
};

export default MediaItem;
