// client/src/component/MainPage/TextRotate.tsx
import React, { useEffect, useState } from "react";

const TextRotate = ({
  dataRotate,
  dataPeriod = 2000,
}: {
  dataRotate: Array<string>;
  dataPeriod?: number;
}) => {
  const [text, setText] = useState("");
  const [timeoutId, setTimeoutId] = useState<any>(0);
  const tick = (textIncoming: string, deleting: boolean, loopNum: number) => {
    var fullText = dataRotate[loopNum % dataRotate.length];
    var futurText = fullText.substring(
      0,
      textIncoming.length + (deleting ? -1 : +1)
    );
    setText(futurText);
    var delta = 200 - Math.random() * 100;
    if (deleting) delta /= 2;
    if (!deleting && futurText === fullText) {
      delta = dataPeriod;
      deleting = true;
    } else if (deleting && futurText === "") {
      deleting = false;
      loopNum = loopNum + 1;
      delta = 400;
    }
    var id = setTimeout(() => {
      tick(futurText, deleting, loopNum);
    }, delta);
    setTimeoutId(id);
  };
  useEffect(() => {
    tick(text, false, 0);
    return () => {
      if (timeoutId) clearTimeout(timeoutId);
    };
    // eslint-disable-next-line
  }, []);
  return (
    <p>
      <span className="txt-rotate">
        <span className="wrap">{text}</span>
      </span>
    </p>
  );
};

export default TextRotate;

// next-gen/src/components/TextRotate.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

const props = defineProps({
  dataRotate: {
    type: Array<string>,
    required: true,
  },
  dataPeriod: {
    type: Number,
    default: 2000,
  },
  className: {
    type: String,
    default: "",
  },
});

const text = ref("");
const timeoutId = ref(0);

const rotate = (textIncoming: string, deleting: boolean, loopNum: number) => {
  var fullText = props.dataRotate[loopNum % props.dataRotate.length];
  var futurText = fullText.substring(
    0,
    textIncoming.length + (deleting ? -1 : +1)
  );
  text.value = futurText;
  var delta = 200 - Math.random() * 100;
  if (deleting) {
    delta /= 2;
  }
  if (!deleting && futurText === fullText) {
    delta = props.dataPeriod;
    deleting = true;
  } else if (deleting && futurText === "") {
    deleting = false;
    loopNum++;
    delta = 500;
  }
  timeoutId.value = setTimeout(() => {
    rotate(futurText, deleting, loopNum);
  }, delta);
};

const stopRotate = () => {
  clearTimeout(timeoutId.value);
};

onMounted(() => {
  rotate(text.value, false, 0);
  return stopRotate;
});
</script>

<template>
  <div class="textRotateWrapper" :class="className">
    <span class="textRotate">
      <span class="textWrap">{{ text }}</span>
    </span>
  </div>
</template>
